export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const SESSION_REPOSITORY = Symbol('SESSION_REPOSITORY');
export const JAR_REPOSITORY = Symbol('JAR_REPOSITORY');
export const INCOME_REPOSITORY = Symbol('INCOME_REPOSITORY');
export const INCOME_DISTRIBUTION_REPOSITORY = Symbol(
  'INCOME_DISTRIBUTION_REPOSITORY',
);
export const EXPENSE_REPOSITORY = Symbol('EXPENSE_REPOSITORY');
export const JAR_BALANCE_REPOSITORY = Symbol('JAR_BALANCE_REPOSITORY');
export const DASHBOARD_REPOSITORY = Symbol('DASHBOARD_REPOSITORY');
export const PASSWORD_HASHER = Symbol('PASSWORD_HASHER');
export const SESSION_TOKEN_SERVICE = Symbol('SESSION_TOKEN_SERVICE');
